{% set name = "blpapi" %}
{% set version = "3.13.1" %}
{% set blpapicpp_linux_version = "3.12.3.1" %}
{% set blpapicpp_win_version = "3.12.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://bloomberg.bintray.com/pip/simple/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: a8c4cf94e2ac8d9ce75158ed4c58999b426e0c104d2de24e5bc854998fca5ae2
  - url: https://bloomberg.bintray.com/BLPAPI-Experimental-Generic/blpapi_cpp_{{ blpapicpp_linux_version }}-linux.tar.gz  # [linux]
    sha256: 3faf881921912de18eec687f47b976d8d924eb77ba0cfcd565b5330ab99a8765  # [linux]
  - url: https://software.tech.bloomberg/BLPAPI-Experimental-Generic/blpapi_cpp_{{ blpapicpp_win_version }}-windows.zip  # [win]
    sha256: 5d494927cc3eab28b7bcfd8ee32a23f0e38a7cd5ab4402cf898ea8fea5040ebc  # [win]

build:
  number: 0
  skip: true  # [osx]
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_linux_version }}_{{ PKG_BUILDNUM }}  # [linux]
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_win_version }}_{{ PKG_BUILDNUM }}  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - blpapi

about:
  home: https://www.bloomberg.com/professional/support/api-library/
  license: Copyright 2012. Bloomberg Finance L.P.
  license_file: License.txt
  summary: 'Python SDK for Bloomberg BLPAPI (<=3.9)'

extra:
  recipe-maintainers:
    - matthewgilbert
