{% set name = "blpapi" %}
{% set version = "3.9.2" %}
{% set version_sha = "4c3cbf3fb63fd338360d55188f6a59568023be6e16531d4bd307ac59a297fd96" %}
{% set blpapicpp_version = "3.8.18.1" %}
{% set blpapicpp_linux_sha = "c6c425f714b461ec618e6900bda8d9b4fc919892538ccfbf8c9a774e9e234fee" %}
{% set blpapicpp_win_sha = "d62e3f109665f027e2ba3117d015c06a20d5e79e273777ef87915c82311d3fec" %}
{% set blpapicpp_osx_sha = "1a74df5f15226aab3fdd7d4f5c765ccfee8cf130d6917962af014a7ac673142f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://bloomberg.bintray.com/pip/simple/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ version_sha }}
  - url: https://software.tech.bloomberg/BLPAPI-Stable-Generic/blpapi_cpp_{{ blpapicpp_version }}-linux.tar.gz  # [linux]
    sha256: {{ blpapicpp_linux_sha }}  # [linux]
  - url: https://software.tech.bloomberg/BLPAPI-Stable-Generic/blpapi_cpp_{{ blpapicpp_version }}-windows.zip  # [win]
    sha256: {{ blpapicpp_win_sha }}  # [win]
  - url: https://software.tech.bloomberg/BLPAPI-Experimental-Generic/blpapi_cpp_{{ blpapicpp_version }}-darwin.tar.gz  # [osx]
    sha256: {{ blpapicpp_osx_sha }}  # [osx]
build:
  number: 1
  string: py{{ CONDA_PY }}_blpapicpp{{ blpapicpp_version }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - blpapi

about:
  home: https://www.bloomberg.com/professional/support/api-library/
  license: Copyright 2012. Bloomberg Finance L.P.
  license_file: License.txt
  summary: 'Python SDK for Bloomberg BLPAPI (<=3.9)'

extra:
  recipe-maintainers:
    - matthewgilbert
