travis:
  secure:
    BINSTAR_TOKEN: NbNKXnJPhzovUbass4wge788V0BkymaY5rAVbGo/jhbu/JA/ok2t5/cKAOX1psAyYmXs0zgIevf1z/bi2mIPWwdI1y2F17DAVMyslHO8PZqIt5YJUvsezoW9if4smWP+iM3wHbB5H+hQZ2AbjVVZangtIn6gn8lDrOXvWOVvi0Q+cFN+F3ITQG7I2v5jwRP/HCThZ8G6z6cwOl7LZbEtXM5wHxyPxWfX4dwL+PE3D8SsnWJFuPSWNOSiBh4tsf6lLKmlBqQDSKavE6Qy4S+LifCVp2khjWpXPT7R6nKRN04ArDhjH/aZ9WHJ87bbeOMbdYLPQSZO9F7sMYHENTYpQljALOVGFtfF7MTpRBD50yOFt35OLP5be61okmI4Ph1jlQ0fqU5aBa2j4ZtBpPqYt+Q+vMSw/wh3/JzJJQSs7crnVK9jax4tnUhMDvLDzhjT2IMy+xTyKrMqHVwUbZ/XdXAQ680Dc1cN0nHGGURAvv1oy4R4TZuexmXjjTJ5jXY20ylk3ov9qa6GE5yvlZYnmxWrM5O5qgFTCfs8eCg72X2KWu3jXMtw48Na6w+c3HHbvayBZtR+duplvJd5/tbzsG+px2/t7wp2SO0Pxf4Jwmde9BZrJnGdgrKFBbZnEQIAhstkuVa/iAZHKC/PNn0J3gWb754b5FtNfy4ypBMWbmk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
